arrowParens: avoid
bracketSpacing: true
endOfLine: auto
htmlWhitespaceSensitivity: strict
jsxBracketSameLine: true
jsxSingleQuote: false
printWidth: 80
proseWrap: preserve
quoteProps: consistent
semi: true
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
vueIndentScriptAndStyle: false
